## Data Preprocessing in Python

# I. Iris data

**1) Importing the librarys**

In [95]:
import pandas as pd
import numpy as np

**2) Importing the datasets**

In [96]:
X = data.drop('Species', axis=1)
y = data['Species']

data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [97]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [98]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

**3) Splitting the dataset into the Training set and Test set**

In [99]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [100]:
print(X_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
23             5.1           3.3            1.7           0.5
125            7.2           3.2            6.0           1.8
114            5.8           2.8            5.1           2.4
105            7.6           3.0            6.6           2.1
109            7.2           3.6            6.1           2.5
..             ...           ...            ...           ...
46             5.1           3.8            1.6           0.2
84             5.4           3.0            4.5           1.5
69             5.6           2.5            3.9           1.1
101            5.8           2.7            5.1           1.9
55             5.7           2.8            4.5           1.3

[120 rows x 4 columns]


In [101]:
print(X_test)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
25             5.0           3.0            1.6           0.2
147            6.5           3.0            5.2           2.0
40             5.0           3.5            1.3           0.3
30             4.8           3.1            1.6           0.2
52             6.9           3.1            4.9           1.5
70             5.9           3.2            4.8           1.8
148            6.2           3.4            5.4           2.3
66             5.6           3.0            4.5           1.5
16             5.4           3.9            1.3           0.4
144            6.7           3.3            5.7           2.5
127            6.1           3.0            4.9           1.8
36             5.5           3.5            1.3           0.2
142            5.8           2.7            5.1           1.9
91             6.1           3.0            4.6           1.4
71             6.1           2.8            4.0           1.3
39      

In [102]:
print(y_train)

23         Iris-setosa
125     Iris-virginica
114     Iris-virginica
105     Iris-virginica
109     Iris-virginica
            ...       
46         Iris-setosa
84     Iris-versicolor
69     Iris-versicolor
101     Iris-virginica
55     Iris-versicolor
Name: Species, Length: 120, dtype: object


In [103]:
print(y_test)

25         Iris-setosa
147     Iris-virginica
40         Iris-setosa
30         Iris-setosa
52     Iris-versicolor
70     Iris-versicolor
148     Iris-virginica
66     Iris-versicolor
16         Iris-setosa
144     Iris-virginica
127     Iris-virginica
36         Iris-setosa
142     Iris-virginica
91     Iris-versicolor
71     Iris-versicolor
39         Iris-setosa
145     Iris-virginica
128     Iris-virginica
77     Iris-versicolor
15         Iris-setosa
62     Iris-versicolor
118     Iris-virginica
121     Iris-virginica
63     Iris-versicolor
34         Iris-setosa
7          Iris-setosa
64     Iris-versicolor
93     Iris-versicolor
38         Iris-setosa
146     Iris-virginica
Name: Species, dtype: object


# II. Data

**1) Importing the librarys**

In [104]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**2) Importing the datasets**

In [105]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [106]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [107]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

**3) Taking care of missing data**

In [108]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [109]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**4) Encoding the Independent Variable**

In [110]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [111]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

**4) Encoding the dependent Variable**

In [112]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [113]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**5) Splitting the dataset into the Training set and Test set**

In [114]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [115]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [116]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [117]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [118]:
print(y_test)

[0 1]


**6) Feature Scaling**

In [119]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [120]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [121]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
